"""saved_recipe

Revision ID: 30450126e1f1
Revises: 4de241788479
Create Date: 2026-08-27 14:49:52.016987

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "30450126e1f1"
down_revision: str | Sequence[str] | None = "4de241788479"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
