"""nullable patch

Revision ID: 97eb19c47eb7
Revises: 725c9c6f3364
Create Date: 2026-08-30 17:42:26.518449

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97eb19c47eb7"
down_revision: str | Sequence[str] | None = "725c9c6f3364"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("users", "birth", existing_type=sa.DATE(), nullable=False)
    op.alter_column("users", "phone_encrypt", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("users", "phone_hash", existing_type=sa.VARCHAR(length=128), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_hash", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.alter_column("users", "phone_encrypt", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.alter_column("users", "birth", existing_type=sa.DATE(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=128), nullable=True)
    # ### end Alembic commands ###
