"""init_db

Revision ID: cffdcaf86354
Revises:
Create Date: 2026-08-25 15:13:28.462255

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cffdcaf86354"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("nickname", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone_encrypt", sa.String(length=128), nullable=True),
        sa.Column("phone_hash", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=10), nullable=False),
        sa.Column("social_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_hash"),
        sa.UniqueConstraint("social_id"),
    )
    op.create_index("ix_user_created_at", "users", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index("ix_user_nickname_lower", "users", [sa.literal_column("lower(nickname)")], unique=True)
    op.create_table(
        "ingredients",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_name", sa.String(length=45), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_id"), "ingredients", ["id"], unique=False)
    op.create_index(op.f("ix_ingredients_user_id"), "ingredients", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingredients_user_id"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_id"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index("ix_user_nickname_lower", table_name="users")
    op.drop_index("ix_user_created_at", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
