"""init_db

Revision ID: d2b70903e14d
Revises: 
Create Date: 2026-05-05 21:05:28.255312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2b70903e14d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_expiry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=45), nullable=False),
    sa.Column('expiry_day', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_expiry_id'), 'ingredients_expiry', ['id'], unique=False)
    op.create_table('non_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_ingredients_id'), 'non_ingredients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('phone_encrypt', sa.String(length=128), nullable=True),
    sa.Column('phone_hash', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('social_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_hash'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index('ix_active_user_recovery', 'users', ['name', 'birth', 'phone_hash'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_user_created_at', 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_user_nickname_lower', 'users', [sa.literal_column('lower(nickname)')], unique=True)
    op.create_table('expiry_deviation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=45), nullable=False),
    sa.Column('deviation_day', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expiry_deviation_logs_id'), 'expiry_deviation_logs', ['id'], unique=False)
    op.create_table('missing_ingredients_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_ingredients_logs_id'), 'missing_ingredients_logs', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_name', sa.String(length=45), nullable=False),
    sa.Column('recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('refrigerator',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refrigerator_id'), 'refrigerator', ['id'], unique=False)
    op.create_index(op.f('ix_refrigerator_user_id'), 'refrigerator', ['user_id'], unique=False)
    op.create_table('shopping_list',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_id'), 'shopping_list', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_list_user_id'), 'shopping_list', ['user_id'], unique=False)
    op.create_table('compartment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refrigerator_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['refrigerator_id'], ['refrigerator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compartment_id'), 'compartment', ['id'], unique=False)
    op.create_index(op.f('ix_compartment_refrigerator_id'), 'compartment', ['refrigerator_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('compartment_id', sa.BigInteger(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=45), nullable=False),
    sa.Column('storage_type', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingredient_user_compartment', 'ingredients', ['user_id', 'compartment_id'], unique=False)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_user_id'), 'ingredients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_user_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index('ix_ingredient_user_compartment', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_compartment_refrigerator_id'), table_name='compartment')
    op.drop_index(op.f('ix_compartment_id'), table_name='compartment')
    op.drop_table('compartment')
    op.drop_index(op.f('ix_shopping_list_user_id'), table_name='shopping_list')
    op.drop_index(op.f('ix_shopping_list_id'), table_name='shopping_list')
    op.drop_table('shopping_list')
    op.drop_index(op.f('ix_refrigerator_user_id'), table_name='refrigerator')
    op.drop_index(op.f('ix_refrigerator_id'), table_name='refrigerator')
    op.drop_table('refrigerator')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_missing_ingredients_logs_id'), table_name='missing_ingredients_logs')
    op.drop_table('missing_ingredients_logs')
    op.drop_index(op.f('ix_expiry_deviation_logs_id'), table_name='expiry_deviation_logs')
    op.drop_table('expiry_deviation_logs')
    op.drop_index('ix_user_nickname_lower', table_name='users')
    op.drop_index('ix_user_created_at', table_name='users')
    op.drop_index('ix_active_user_recovery', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index(op.f('ix_non_ingredients_id'), table_name='non_ingredients')
    op.drop_table('non_ingredients')
    op.drop_index(op.f('ix_ingredients_expiry_id'), table_name='ingredients_expiry')
    op.drop_table('ingredients_expiry')
    # ### end Alembic commands ###
