"""saved_recipe

Revision ID: fac4e22ce120
Revises: 30450126e1f1
Create Date: 2026-08-27 14:54:24.709213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fac4e22ce120"
down_revision: str | Sequence[str] | None = "30450126e1f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_recipe",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=512), nullable=False),
        sa.Column("recipe_name", sa.String(length=256), nullable=False),
        sa.Column("recipe_difficulty", sa.String(length=64), nullable=True),
        sa.Column("time", sa.String(length=64), nullable=True),
        sa.Column(
            "snapshot", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source", "source_id", name="uq_saved_recipes_user_source"),
    )
    op.create_index(op.f("ix_saved_recipe_user_id"), "saved_recipe", ["user_id"], unique=False)
    op.create_index(
        "ix_saved_recipes_user_created", "saved_recipe", ["user_id", sa.literal_column("created_at DESC")], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_saved_recipes_user_created", table_name="saved_recipe")
    op.drop_index(op.f("ix_saved_recipe_user_id"), table_name="saved_recipe")
    op.drop_table("saved_recipe")
    # ### end Alembic commands ###
