"""initial_migration

Revision ID: 1d6e1ba7e67a
Revises:
Create Date: 2026-02-20 12:15:47.705091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d6e1ba7e67a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "compartment", "id", existing_type=sa.BIGINT(), server_default=None, existing_nullable=False, autoincrement=True
    )
    op.drop_index(op.f("idx_compartment_refrigerator_id"), table_name="compartment")
    op.create_index(op.f("ix_compartment_id"), "compartment", ["id"], unique=False)
    op.alter_column(
        "expiry_deviation_logs",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_expiry_deviation_logs_user_id"), table_name="expiry_deviation_logs")
    op.create_index(op.f("ix_expiry_deviation_logs_id"), "expiry_deviation_logs", ["id"], unique=False)
    op.alter_column(
        "ingredients", "id", existing_type=sa.BIGINT(), server_default=None, existing_nullable=False, autoincrement=True
    )
    op.create_index(op.f("ix_ingredients_id"), "ingredients", ["id"], unique=False)
    op.drop_constraint(op.f("fk_ingredients_compartment"), "ingredients", type_="foreignkey")
    op.create_foreign_key(None, "ingredients", "compartment", ["compartment_id"], ["id"])
    op.alter_column(
        "ingredients_expiry",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_ingredients_expiry_lookup"), table_name="ingredients_expiry")
    op.create_index(op.f("ix_ingredients_expiry_id"), "ingredients_expiry", ["id"], unique=False)
    op.alter_column(
        "missing_ingredients_logs",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_missing_ingredients_logs_user_id"), table_name="missing_ingredients_logs")
    op.create_index(op.f("ix_missing_ingredients_logs_id"), "missing_ingredients_logs", ["id"], unique=False)
    op.alter_column(
        "non_ingredients",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f("ix_non_ingredients_id"), "non_ingredients", ["id"], unique=False)
    op.alter_column(
        "recipes", "id", existing_type=sa.BIGINT(), server_default=None, existing_nullable=False, autoincrement=True
    )
    op.drop_index(op.f("idx_recipes_user_id"), table_name="recipes")
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.alter_column(
        "refrigerator",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_refrigerator_user_id"), table_name="refrigerator")
    op.create_index(op.f("ix_refrigerator_id"), "refrigerator", ["id"], unique=False)
    op.alter_column(
        "shopping_list",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_shopping_user_id"), table_name="shopping_list")
    op.create_index(op.f("ix_shopping_list_id"), "shopping_list", ["id"], unique=False)
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_index(op.f("idx_users_nickname"), table_name="users")
    op.create_index(
        "ix_active_user_recovery",
        "users",
        ["name", "birth", "phone_hash"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_active_user_social",
        "users",
        ["provider", "social_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_user_created_at", "users", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index("ix_user_nickname_lower", "users", [sa.literal_column("lower(nickname)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_nickname_lower", table_name="users")
    op.drop_index("ix_user_created_at", table_name="users")
    op.drop_index("ix_active_user_social", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index("ix_active_user_recovery", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index(op.f("idx_users_nickname"), "users", ["nickname"], unique=False)
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.drop_index(op.f("ix_shopping_list_id"), table_name="shopping_list")
    op.create_index(op.f("idx_shopping_user_id"), "shopping_list", ["user_id"], unique=False)
    op.alter_column(
        "shopping_list",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_refrigerator_id"), table_name="refrigerator")
    op.create_index(op.f("idx_refrigerator_user_id"), "refrigerator", ["user_id"], unique=False)
    op.alter_column(
        "refrigerator",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.create_index(op.f("idx_recipes_user_id"), "recipes", ["user_id"], unique=False)
    op.alter_column(
        "recipes",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_non_ingredients_id"), table_name="non_ingredients")
    op.alter_column(
        "non_ingredients",
        "id",
        existing_type=sa.Integer(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_missing_ingredients_logs_id"), table_name="missing_ingredients_logs")
    op.create_index(op.f("idx_missing_ingredients_logs_user_id"), "missing_ingredients_logs", ["user_id"], unique=False)
    op.alter_column(
        "missing_ingredients_logs",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_ingredients_expiry_id"), table_name="ingredients_expiry")
    op.create_index(
        op.f("idx_ingredients_expiry_lookup"), "ingredients_expiry", ["ingredient_name", "storage_type"], unique=False
    )
    op.alter_column(
        "ingredients_expiry",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(None, "ingredients", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ingredients_compartment"),
        "ingredients",
        "compartment",
        ["compartment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_ingredients_id"), table_name="ingredients")
    op.alter_column(
        "ingredients",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_expiry_deviation_logs_id"), table_name="expiry_deviation_logs")
    op.create_index(op.f("idx_expiry_deviation_logs_user_id"), "expiry_deviation_logs", ["user_id"], unique=False)
    op.alter_column(
        "expiry_deviation_logs",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_compartment_id"), table_name="compartment")
    op.create_index(op.f("idx_compartment_refrigerator_id"), "compartment", ["refrigerator_id"], unique=False)
    op.alter_column(
        "compartment",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(
            always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
